let perfumes = [
  {
    id: 1,
    nombre: "Elegance",
    categoria: "Floral",
    imagen: "perfume1.jpg",
    codigo: "EleG4nc3",
    precio: 155000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 2,
    nombre: "Blue Ocean",
    categoria: "Fresco",
    imagen: "perfume2.jpg",
    codigo: "BlueOc34n",
    precio: 128000,
    volumen: 100,
    intensidad: "Baja",
  },
  {
    id: 3,
    nombre: "Midnight Dream",
    categoria: "Oriental",
    imagen: "perfume3.jpg",
    codigo: "MidNi28Ht",
    precio: 210000,
    volumen: 75,
    intensidad: "Alta",
  },
  {
    id: 4,
    nombre: "Pure Rose",
    categoria: "Floral",
    imagen: "perfume4.jpg",
    codigo: "PureR0s3",
    precio: 175000,
    volumen: 50,
    intensidad: "Media-Alta",
  },
  {
    id: 5,
    nombre: "Amber Wood",
    categoria: "Amaderado",
    imagen: "perfume5.jpg",
    codigo: "AmberW00d",
    precio: 195000,
    volumen: 100,
    intensidad: "Alta",
  },
  {
    id: 6,
    nombre: "Fresh Citrus",
    categoria: "Cítrico",
    imagen: "perfume6.jpg",
    codigo: "FreshC1t",
    precio: 135000,
    volumen: 75,
    intensidad: "Media-Baja",
  },
  {
    id: 7,
    nombre: "Royal Oud",
    categoria: "Oriental",
    imagen: "perfume7.jpg",
    codigo: "RoyalO0ud",
    precio: 250000,
    volumen: 50,
    intensidad: "Alta",
  },
  {
    id: 8,
    nombre: "Summer Breeze",
    categoria: "Fresco",
    imagen: "perfume8.jpg",
    codigo: "SummEr56",
    precio: 120000,
    volumen: 100,
    intensidad: "Baja",
  },
  {
    id: 9,
    nombre: "Vanilla Dream",
    categoria: "Oriental",
    imagen: "perfume9.jpg",
    codigo: "VaniL1a22",
    precio: 165000,
    volumen: 75,
    intensidad: "Media",
  },
  {
    id: 10,
    nombre: "Cedar Essence",
    categoria: "Amaderado",
    imagen: "perfume10.jpg",
    codigo: "CedarE45s",
    precio: 185000,
    volumen: 100,
    intensidad: "Media-Alta",
  },
  {
    id: 11,
    nombre: "Lavender Fields",
    categoria: "Floral",
    imagen: "perfume1.jpg",
    codigo: "LavEnd3r",
    precio: 142000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 12,
    nombre: "Ocean Waves",
    categoria: "Fresco",
    imagen: "perfume2.jpg",
    codigo: "OceanW4ve",
    precio: 138000,
    volumen: 75,
    intensidad: "Media-Baja",
  },
  {
    id: 13,
    nombre: "Desert Rose",
    categoria: "Oriental",
    imagen: "perfume3.jpg",
    codigo: "DesertR0se",
    precio: 198000,
    volumen: 50,
    intensidad: "Alta",
  },
  {
    id: 14,
    nombre: "Green Tea",
    categoria: "Fresco",
    imagen: "perfume4.jpg",
    codigo: "GreenT3a",
    precio: 115000,
    volumen: 100,
    intensidad: "Baja",
  },
  {
    id: 15,
    nombre: "Dark Wood",
    categoria: "Amaderado",
    imagen: "perfume5.jpg",
    codigo: "DarkW00d",
    precio: 205000,
    volumen: 75,
    intensidad: "Alta",
  },
  {
    id: 16,
    nombre: "Lemon Zest",
    categoria: "Cítrico",
    imagen: "perfume6.jpg",
    codigo: "LemonZ3st",
    precio: 125000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 17,
    nombre: "Mystic Night",
    categoria: "Oriental",
    imagen: "perfume7.jpg",
    codigo: "MysticN1te",
    precio: 220000,
    volumen: 100,
    intensidad: "Alta",
  },
  {
    id: 18,
    nombre: "Spring Blossom",
    categoria: "Floral",
    imagen: "perfume8.jpg",
    codigo: "Spring12B",
    precio: 145000,
    volumen: 75,
    intensidad: "Media",
  },
  {
    id: 19,
    nombre: "Sandalwood",
    categoria: "Amaderado",
    imagen: "perfume9.jpg",
    codigo: "SandaL45",
    precio: 190000,
    volumen: 50,
    intensidad: "Media-Alta",
  },
  {
    id: 20,
    nombre: "Orange Splash",
    categoria: "Cítrico",
    imagen: "perfume10.jpg",
    codigo: "OrangE67",
    precio: 130000,
    volumen: 100,
    intensidad: "Media-Baja",
  },
  {
    id: 21,
    nombre: "Jasmine Dream",
    categoria: "Floral",
    imagen: "perfume1.jpg",
    codigo: "JasmiN34",
    precio: 160000,
    volumen: 75,
    intensidad: "Media",
  },
  {
    id: 22,
    nombre: "Cool Mint",
    categoria: "Fresco",
    imagen: "perfume2.jpg",
    codigo: "CoolM1nt",
    precio: 118000,
    volumen: 50,
    intensidad: "Baja",
  },
  {
    id: 23,
    nombre: "Amber Rose",
    categoria: "Oriental",
    imagen: "perfume3.jpg",
    codigo: "AmberR0se",
    precio: 195000,
    volumen: 100,
    intensidad: "Alta",
  },
  {
    id: 24,
    nombre: "Pine Forest",
    categoria: "Amaderado",
    imagen: "perfume4.jpg",
    codigo: "PineF0r3st",
    precio: 175000,
    volumen: 75,
    intensidad: "Media-Alta",
  },
  {
    id: 25,
    nombre: "Citrus Burst",
    categoria: "Cítrico",
    imagen: "perfume5.jpg",
    codigo: "CitrusB78",
    precio: 140000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 26,
    nombre: "White Orchid",
    categoria: "Floral",
    imagen: "perfume6.jpg",
    codigo: "WhiteOr45",
    precio: 180000,
    volumen: 100,
    intensidad: "Media-Alta",
  },
  {
    id: 27,
    nombre: "Mediterranean",
    categoria: "Fresco",
    imagen: "perfume7.jpg",
    codigo: "MediT3rr",
    precio: 150000,
    volumen: 75,
    intensidad: "Media",
  },
  {
    id: 28,
    nombre: "Velvet Musk",
    categoria: "Oriental",
    imagen: "perfume8.jpg",
    codigo: "VelveT56",
    precio: 210000,
    volumen: 50,
    intensidad: "Alta",
  },
  {
    id: 29,
    nombre: "Cedar & Sage",
    categoria: "Amaderado",
    imagen: "perfume9.jpg",
    codigo: "CedarS4ge",
    precio: 195000,
    volumen: 100,
    intensidad: "Media-Alta",
  },
  {
    id: 30,
    nombre: "Grapefruit Zest",
    categoria: "Cítrico",
    imagen: "perfume10.jpg",
    codigo: "GrapeF67",
    precio: 135000,
    volumen: 75,
    intensidad: "Media",
  },
  {
    id: 31,
    nombre: "Peony Bloom",
    categoria: "Floral",
    imagen: "perfume1.jpg",
    codigo: "PeonyB12",
    precio: 165000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 32,
    nombre: "Arctic Breeze",
    categoria: "Fresco",
    imagen: "perfume2.jpg",
    codigo: "ArctiC45",
    precio: 125000,
    volumen: 100,
    intensidad: "Baja",
  },
  {
    id: 33,
    nombre: "Saffron Gold",
    categoria: "Oriental",
    imagen: "perfume3.jpg",
    codigo: "SaffroN23",
    precio: 235000,
    volumen: 75,
    intensidad: "Alta",
  },
  {
    id: 34,
    nombre: "Mahogany",
    categoria: "Amaderado",
    imagen: "perfume4.jpg",
    codigo: "Mahog4ny",
    precio: 185000,
    volumen: 50,
    intensidad: "Media-Alta",
  },
  {
    id: 35,
    nombre: "Lime Fresh",
    categoria: "Cítrico",
    imagen: "perfume5.jpg",
    codigo: "LimeFr3sh",
    precio: 130000,
    volumen: 75,
    intensidad: "Media-Baja",
  },
  {
    id: 36,
    nombre: "Cherry Blossom",
    categoria: "Floral",
    imagen: "perfume6.jpg",
    codigo: "CherryB78",
    precio: 155000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 37,
    nombre: "Mountain Air",
    categoria: "Fresco",
    imagen: "perfume7.jpg",
    codigo: "MountA1r",
    precio: 140000,
    volumen: 100,
    intensidad: "Media",
  },
  {
    id: 38,
    nombre: "Arabian Nights",
    categoria: "Oriental",
    imagen: "perfume8.jpg",
    codigo: "ArabiaN56",
    precio: 225000,
    volumen: 75,
    intensidad: "Alta",
  },
  {
    id: 39,
    nombre: "Rosewood",
    categoria: "Amaderado",
    imagen: "perfume9.jpg",
    codigo: "RoseW00d",
    precio: 190000,
    volumen: 50,
    intensidad: "Media-Alta",
  },
  {
    id: 40,
    nombre: "Bergamot Breeze",
    categoria: "Cítrico",
    imagen: "perfume10.jpg",
    codigo: "BergaM0t",
    precio: 145000,
    volumen: 100,
    intensidad: "Media",
  },
  {
    id: 41,
    nombre: "Lily Valley",
    categoria: "Floral",
    imagen: "perfume1.jpg",
    codigo: "LilyV4l",
    precio: 160000,
    volumen: 75,
    intensidad: "Media",
  },
  {
    id: 42,
    nombre: "Ocean Breeze",
    categoria: "Fresco",
    imagen: "perfume2.jpg",
    codigo: "OceanBr34",
    precio: 135000,
    volumen: 50,
    intensidad: "Baja",
  },
  {
    id: 43,
    nombre: "Mystic Amber",
    categoria: "Oriental",
    imagen: "perfume3.jpg",
    codigo: "MystiC78",
    precio: 200000,
    volumen: 100,
    intensidad: "Alta",
  },
  {
    id: 44,
    nombre: "Cedar Noir",
    categoria: "Amaderado",
    imagen: "perfume4.jpg",
    codigo: "CedarN01r",
    precio: 185000,
    volumen: 75,
    intensidad: "Media-Alta",
  },
  {
    id: 45,
    nombre: "Mandarin Fresh",
    categoria: "Cítrico",
    imagen: "perfume5.jpg",
    codigo: "MandaR1n",
    precio: 130000,
    volumen: 50,
    intensidad: "Media",
  },
  {
    id: 46,
    nombre: "Violet Dreams",
    categoria: "Floral",
    imagen: "perfume6.jpg",
    codigo: "VioleT45",
    precio: 170000,
    volumen: 100,
    intensidad: "Media-Alta",
  },
  {
    id: 47,
    nombre: "Aqua Fresh",
    categoria: "Fresco",
    imagen: "perfume7.jpg",
    codigo: "AquaFr3sh",
    precio: 140000,
    volumen: 75,
    intensidad: "Media-Baja",
  },
  {
    id: 48,
    nombre: "Spice Market",
    categoria: "Oriental",
    imagen: "perfume8.jpg",
    codigo: "SpiceM4r",
    precio: 215000,
    volumen: 50,
    intensidad: "Alta",
  },
  {
    id: 49,
    nombre: "Ebony Wood",
    categoria: "Amaderado",
    imagen: "perfume9.jpg",
    codigo: "EbonyW00d",
    precio: 195000,
    volumen: 100,
    intensidad: "Media-Alta",
  },
  {
    id: 50,
    nombre: "Lemon Verbena",
    categoria: "Cítrico",
    imagen: "perfume10.jpg",
    codigo: "LemonV3r",
    precio: 150000,
    volumen: 75,
    intensidad: "Media",
  },
];
// Función para guardar los perfumes en el localStorage
function guardarPerfumes() {
  localStorage.setItem("perfumes", JSON.stringify(perfumes));
}
// Función para cargar los perfumes desde el localStorage
function cargarPerfumes() {
  const perfumesGuardados = localStorage.getItem("perfumes");
  if (perfumesGuardados) {
    perfumes = JSON.parse(perfumesGuardados);
  } else {
    // Si no hay perfumes guardados, guardamos los iniciales
    guardarPerfumes();
  }
  return perfumes;
}
// Función para agregar un nuevo perfume
function agregarPerfume(perfume) {
  // Generamos un ID único
  perfume.id =
    perfumes.length > 0 ? Math.max(...perfumes.map((p) => p.id)) + 1 : 1;
  perfumes.push(perfume);
  guardarPerfumes();
  return perfume;
}
// Función para formatear el precio en pesos colombianos
function formatearPrecio(precio) {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(precio);
}
// Inicializamos la base de datos al cargar el script
cargarPerfumes();
